apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  selector:
    service: reverseproxy
    app: '8080'
  ports:
  - port: 8080
    targetPort: 808i

